require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.cpu")
require("items.widgets.meeting")
require("items.widgets.prs")
require("items.widgets.slack")
require("items.widgets.claude")
