//! Global durable tab registry stored at `~/.tmux-tabs.yml`.
//!
//! This intentionally uses a tiny YAML subset writer/parser instead of adding
//! dependencies: the file shape is stable, agent-readable, and generated by us.

use std::collections::HashSet;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::model::Window;

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum TabStatus {
    #[default]
    Unknown,
    Running,
    WaitingForInput,
    Blocked,
    Done,
    Dead,
}

impl TabStatus {
    pub fn as_str(self) -> &'static str {
        match self {
            TabStatus::Unknown => "unknown",
            TabStatus::Running => "running",
            TabStatus::WaitingForInput => "waiting_for_input",
            TabStatus::Blocked => "blocked",
            TabStatus::Done => "done",
            TabStatus::Dead => "dead",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "unknown" => Some(TabStatus::Unknown),
            "running" => Some(TabStatus::Running),
            "waiting_for_input" => Some(TabStatus::WaitingForInput),
            "blocked" => Some(TabStatus::Blocked),
            "done" => Some(TabStatus::Done),
            "dead" => Some(TabStatus::Dead),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct TabRecord {
    pub tab_id: String,
    pub session: String,
    pub window_id: String,
    pub window_index: String,
    pub pane_id: String,
    pub name: String,
    pub path: String,
    pub command: String,
    pub status: TabStatus,
    pub resume_command: String,
    pub last_seen: String,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct TabRegistry {
    pub tabs: Vec<TabRecord>,
}

impl TabRegistry {
    pub fn upsert_live(&mut self, session: &str, window: &Window, now: &str) {
        if window.tab_id.is_empty() {
            return;
        }
        let idx = match self.tabs.iter().position(|t| t.tab_id == window.tab_id) {
            Some(i) => i,
            None => {
                self.tabs.push(TabRecord {
                    tab_id: window.tab_id.clone(),
                    ..Default::default()
                });
                self.tabs.len() - 1
            }
        };
        let record = &mut self.tabs[idx];
        record.session = session.to_string();
        record.window_id = window.window_id.clone();
        record.window_index = window.index.clone();
        record.pane_id = window.pane.clone();
        record.name = window.name.clone();
        record.path = window.path.clone();
        record.command = window.command.clone();
        if record.status == TabStatus::Dead {
            record.status = TabStatus::Unknown;
        }
        record.last_seen = now.to_string();
    }

    pub fn refresh_live(&mut self, session: &str, windows: &[Window], now: &str) {
        let live: HashSet<String> = windows.iter().map(|w| w.tab_id.clone()).collect();
        for window in windows {
            self.upsert_live(session, window, now);
        }
        for record in &mut self.tabs {
            if record.session == session && !live.contains(&record.tab_id) {
                record.status = TabStatus::Dead;
            }
        }
    }

    pub fn set_status(&mut self, tab_id: &str, status: TabStatus) -> bool {
        let Some(record) = self.tabs.iter_mut().find(|t| t.tab_id == tab_id) else {
            return false;
        };
        record.status = status;
        true
    }

    pub fn set_resume(&mut self, tab_id: &str, command: &str) -> bool {
        let Some(record) = self.tabs.iter_mut().find(|t| t.tab_id == tab_id) else {
            return false;
        };
        record.resume_command = command.to_string();
        true
    }

    pub fn find(&self, tab_id: &str) -> Option<&TabRecord> {
        self.tabs.iter().find(|t| t.tab_id == tab_id)
    }

    pub fn to_yaml(&self) -> String {
        let mut out = String::from("tabs:\n");
        for tab in &self.tabs {
            out.push_str(&format!("  {}:\n", yaml_key(&tab.tab_id)));
            out.push_str(&yaml_field("tab_id", &tab.tab_id));
            out.push_str(&yaml_field("session", &tab.session));
            out.push_str(&yaml_field("window_id", &tab.window_id));
            out.push_str(&yaml_field("window_index", &tab.window_index));
            out.push_str(&yaml_field("pane_id", &tab.pane_id));
            out.push_str(&yaml_field("name", &tab.name));
            out.push_str(&yaml_field("path", &tab.path));
            out.push_str(&yaml_field("command", &tab.command));
            out.push_str(&yaml_field("status", tab.status.as_str()));
            out.push_str(&yaml_field("resume_command", &tab.resume_command));
            out.push_str(&yaml_field("last_seen", &tab.last_seen));
        }
        out
    }

    pub fn from_yaml(text: &str) -> Self {
        let mut registry = TabRegistry::default();
        let mut current: Option<TabRecord> = None;
        for line in text.lines() {
            if line.trim().is_empty() || line.trim() == "tabs:" {
                continue;
            }
            if line.starts_with("  ") && !line.starts_with("    ") && line.trim_end().ends_with(':')
            {
                if let Some(record) = current.take() {
                    registry.tabs.push(record);
                }
                let key = line.trim().trim_end_matches(':').trim_matches('"');
                current = Some(TabRecord {
                    tab_id: unescape_yaml(key),
                    ..Default::default()
                });
                continue;
            }
            if let Some(record) = current.as_mut() {
                if let Some((key, value)) = parse_field(line) {
                    apply_field(record, &key, &value);
                }
            }
        }
        if let Some(record) = current.take() {
            registry.tabs.push(record);
        }
        registry
    }

    pub fn to_json(&self) -> String {
        let mut out = String::from("{\"tabs\":[");
        for (i, tab) in self.tabs.iter().enumerate() {
            if i > 0 {
                out.push(',');
            }
            out.push_str(&tab.to_json());
        }
        out.push_str("]}\n");
        out
    }
}

impl TabRecord {
    pub fn to_json(&self) -> String {
        format!(
            "{{\"tab_id\":\"{}\",\"session\":\"{}\",\"window_id\":\"{}\",\"window_index\":\"{}\",\"pane_id\":\"{}\",\"name\":\"{}\",\"path\":\"{}\",\"command\":\"{}\",\"status\":\"{}\",\"resume_command\":\"{}\",\"last_seen\":\"{}\"}}",
            json_escape(&self.tab_id),
            json_escape(&self.session),
            json_escape(&self.window_id),
            json_escape(&self.window_index),
            json_escape(&self.pane_id),
            json_escape(&self.name),
            json_escape(&self.path),
            json_escape(&self.command),
            self.status.as_str(),
            json_escape(&self.resume_command),
            json_escape(&self.last_seen),
        )
    }
}

pub fn registry_path(home: &str) -> PathBuf {
    PathBuf::from(home).join(".tmux-tabs.yml")
}

pub fn now_string() -> String {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs().to_string())
        .unwrap_or_else(|_| "0".to_string())
}

pub fn generated_tab_id(seed: &str) -> String {
    let mut hash: u64 = 1469598103934665603;
    for b in seed.as_bytes() {
        hash ^= *b as u64;
        hash = hash.wrapping_mul(1099511628211);
    }
    for b in now_string().as_bytes() {
        hash ^= *b as u64;
        hash = hash.wrapping_mul(1099511628211);
    }
    format!("tab_{hash:x}")
}

pub fn load(path: &Path) -> TabRegistry {
    fs::read_to_string(path)
        .map(|text| TabRegistry::from_yaml(&text))
        .unwrap_or_default()
}

pub fn save(path: &Path, registry: &TabRegistry) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, registry.to_yaml())
}

fn yaml_key(s: &str) -> String {
    if s.chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        s.to_string()
    } else {
        format!("\"{}\"", escape_yaml(s))
    }
}

fn yaml_field(key: &str, value: &str) -> String {
    format!("    {key}: \"{}\"\n", escape_yaml(value))
}

fn escape_yaml(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn unescape_yaml(s: &str) -> String {
    let mut out = String::new();
    let mut escaped = false;
    for c in s.chars() {
        if escaped {
            out.push(c);
            escaped = false;
        } else if c == '\\' {
            escaped = true;
        } else {
            out.push(c);
        }
    }
    out
}

fn parse_field(line: &str) -> Option<(String, String)> {
    let trimmed = line.trim();
    let colon = trimmed.find(':')?;
    let key = trimmed[..colon].to_string();
    let raw = trimmed[colon + 1..].trim();
    let value = raw.trim_matches('"');
    Some((key, unescape_yaml(value)))
}

fn apply_field(record: &mut TabRecord, key: &str, value: &str) {
    match key {
        "tab_id" => record.tab_id = value.to_string(),
        "session" => record.session = value.to_string(),
        "window_id" => record.window_id = value.to_string(),
        "window_index" => record.window_index = value.to_string(),
        "pane_id" => record.pane_id = value.to_string(),
        "name" => record.name = value.to_string(),
        "path" => record.path = value.to_string(),
        "command" => record.command = value.to_string(),
        "status" => record.status = TabStatus::parse(value).unwrap_or(TabStatus::Unknown),
        "resume_command" => record.resume_command = value.to_string(),
        "last_seen" => record.last_seen = value.to_string(),
        _ => {}
    }
}

fn json_escape(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => {}
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn record(id: &str) -> TabRecord {
        TabRecord {
            tab_id: id.into(),
            session: "main".into(),
            window_id: "@7".into(),
            window_index: "2".into(),
            pane_id: "%3".into(),
            name: "Overage Monitor Decision".into(),
            path: "/repo".into(),
            command: "pi".into(),
            status: TabStatus::WaitingForInput,
            resume_command: "pi resume abc123".into(),
            last_seen: "123".into(),
        }
    }

    #[test]
    fn status_parse_roundtrip() {
        for status in [
            TabStatus::Unknown,
            TabStatus::Running,
            TabStatus::WaitingForInput,
            TabStatus::Blocked,
            TabStatus::Done,
            TabStatus::Dead,
        ] {
            assert_eq!(TabStatus::parse(status.as_str()), Some(status));
        }
        assert_eq!(TabStatus::parse("nope"), None);
    }

    #[test]
    fn yaml_roundtrip_preserves_records() {
        let registry = TabRegistry {
            tabs: vec![record("tab_abc")],
        };

        assert_eq!(TabRegistry::from_yaml(&registry.to_yaml()), registry);
    }

    #[test]
    fn json_output_contains_status_and_resume_command() {
        let registry = TabRegistry {
            tabs: vec![record("tab_abc")],
        };
        let json = registry.to_json();

        assert!(json.contains("\"status\":\"waiting_for_input\""));
        assert!(json.contains("\"resume_command\":\"pi resume abc123\""));
    }

    #[test]
    fn refresh_marks_missing_session_tabs_dead() {
        let mut registry = TabRegistry {
            tabs: vec![record("tab_abc")],
        };

        registry.refresh_live("main", &[], "456");

        assert_eq!(registry.tabs[0].status, TabStatus::Dead);
    }
}
